### PR TITLE
Update general.py

### PR DESCRIPTION
**Pull request by LEQUI000**
update links and indentations.

PLEASE REVIEW. NOT SURE IF I MISSED AN INDENTATION

### CODE REVIEW

**Review by geraldbrent1 — CHANGES_REQUESTED** [review]
Check indentation on commit lines 293-300. Different in master.

**Comment by geraldbrent1** [comment]
Check lines 293-300. Indentation is different in master

**Review by LEQUI000 — COMMENTED** [review]
Seems okay?

**Review by geraldbrent1 — APPROVED** [review]
Fat request, but looks like it won't break anything.

**Pull request merged**
